# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_import_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='import_Order',
            new_name='import_order',
        ),
    ]
