# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('telephone2', models.CharField(max_length=11, verbose_name='联系电话2')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '供应商联系人信息',
                'verbose_name_plural': '供应商联系人信息',
            },
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='订单号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('container', models.SmallIntegerField(default=0, verbose_name='货柜数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='单价')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('push_state', models.BooleanField(default=False, verbose_name='发布状态')),
                ('file', models.FileField(blank=True, upload_to='purchase/%Y%m', verbose_name='相关文件')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '进口代理订单',
                'verbose_name_plural': '进口代理订单',
            },
        ),
        migrations.CreateModel(
            name='ImportOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='编号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='purchase.ImportOrder', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '进口代理订单明细',
                'verbose_name_plural': '进口代理订单明细',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, unique=True, verbose_name='公司名称')),
                ('type', models.CharField(choices=[('import', '进口代理'), ('quarry', '矿山'), ('trading', '贸易公司')], max_length=18, verbose_name='类型')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='地址')),
                ('last_date', models.DateField(verbose_name='最后交易日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.AddField(
            model_name='importorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_order', to='purchase.Supply', verbose_name='代理公司'),
        ),
    ]
