# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20170322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='purchase.ImportOrder', unique=True, verbose_name='订单号'),
        ),
    ]
